name: ci

on:
  push:
    branches: [ addCI ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev build-essential libmicrohttpd-dev sqlite3

      - name: Compile Tests
        working-directory: ./backend/src/tests
        run: |
          clang -o test_runner \
          tests.c \
          ../../user_creds.c \
          ../munit.c \
          -I ../../munit \
          -lmicrohttpd \
          -lsodium \
          -lsqlite3

      - name: Run Tests
        run: ./backend/src/tests/test_runner

